name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop
      - feat/docs-site
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: npm run build:svelte

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './packages/svelte/build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
